directories:
  output: ../../release
  buildResources: assets
appId: com.cadence.app
productName: Cadence
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
win:
  target: nsis
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 28.3.3
